"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FOCUS_LIBRARIES, FOCUS_MODES, type FocusItem } from "../../../lib/focus-library";
const ROUNDS=20, GRID_SIZE=36;
function pick<T>(a:T[]){return a[Math.floor(Math.random()*a.length)];}
function makePalette(mode:string,target:FocusItem){const pool=FOCUS_LIBRARIES[mode].filter(x=>x.id!==target.id);const out=[target];while(out.length<Math.min(8,pool.length+1)){const x=pick(pool);if(!out.some(y=>y.id===x.id))out.push(x);}return out.sort(()=>Math.random()-.5);}
export default function FocusChallenge(){
 const [round,setRound]=useState(0),[mode,setMode]=useState("shapes"),[target,setTarget]=useState<FocusItem>(FOCUS_LIBRARIES.shapes[0]),[targetCell,setTargetCell]=useState(-1),[visible,setVisible]=useState(false),[started,setStarted]=useState(false),[finished,setFinished]=useState(false),[hits,setHits]=useState(0),[mistakes,setMistakes]=useState(0),[streak,setStreak]=useState(0),[bestStreak,setBestStreak]=useState(0),[reactionTotal,setReactionTotal]=useState(0),[shownAt,setShownAt]=useState(0),[palette,setPalette]=useState<FocusItem[]>([]);
 const difficulty=Math.min(1,round/(ROUNDS-1)); const visibleMs=Math.round(1050-difficulty*620);
 const score=useMemo(()=>{if(!finished)return 0;const accuracy=hits/Math.max(1,hits+mistakes),avg=reactionTotal/Math.max(1,hits),speed=Math.max(0,1-avg/1500),streakBonus=Math.min(10,bestStreak*.8);return Math.round(Math.min(100,accuracy*65+speed*25+streakBonus));},[finished,hits,mistakes,reactionTotal,bestStreak]);
 const createRound=useCallback(()=>{const nextMode=pick(FOCUS_MODES);const nextTarget=pick(FOCUS_LIBRARIES[nextMode]);setMode(nextMode);setTarget(nextTarget);setPalette(makePalette(nextMode,nextTarget));setTargetCell(Math.floor(Math.random()*GRID_SIZE));setVisible(true);setShownAt(performance.now());window.setTimeout(()=>setVisible(false),visibleMs);},[visibleMs]);
 const start=()=>{setStarted(true);setFinished(false);setRound(0);setHits(0);setMistakes(0);setStreak(0);setBestStreak(0);setReactionTotal(0);window.setTimeout(createRound,350);};
 const choose=(index:number)=>{if(!started||finished||!visible)return;const reaction=performance.now()-shownAt;if(index===targetCell){const ns=streak+1;setHits(v=>v+1);setStreak(ns);setBestStreak(v=>Math.max(v,ns));setReactionTotal(v=>v+reaction);}else{setMistakes(v=>v+1);setStreak(0);}setVisible(false);if(round>=ROUNDS-1)setFinished(true);else{setRound(v=>v+1);window.setTimeout(createRound,220+Math.random()*520);}};
 useEffect(()=>{if(!started||finished)return;const onKey=(e:KeyboardEvent)=>{const n=Number(e.key)-1;if(n>=0&&n<GRID_SIZE)choose(n)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);});
 useEffect(()=>{if(!finished)return;const previous=JSON.parse(window.localStorage.getItem("forge.metrics")||"[[\"Focus\",0],[\"Control\",0],[\"Patience\",0],[\"Persistence\",0],[\"Consistency\",0]]") as [string,number][];const next=previous.map(([n,v])=>n==="Focus"?[n,Math.max(v,score)]:[n,v]);window.localStorage.setItem("forge.metrics",JSON.stringify(next));window.localStorage.setItem("forge.lastFocus",String(score));window.localStorage.setItem("forge.sessions",String(Number(window.localStorage.getItem("forge.sessions")||0)+1));},[finished,score]);
 return <main className="game-shell"><div className="game-topbar"><Link href="/" className="game-back">← FORGE</Link><div className="game-progress">{started&&!finished ? (round+1)+"/"+ROUNDS : "FOCUS"}</div></div>
 {!started&&!finished&&<section className="game-intro"><div className="eyebrow">FOCUS · VISUAL SEARCH</div><h1>Find it before it vanishes.</h1><p>The library changes every round. Shapes, emojis, animals, food, vehicles and flags can all appear. Learn the visual rule quickly, then act before the target disappears.</p><div className="rule-pills"><span>6 visual families</span><span>36 positions</span><span>Gets faster</span></div><button className="btn btn-primary" onClick={start}>Begin Focus</button></section>}
 {started&&!finished&&<section className="game-stage"><div className="target-card"><span>FIND THIS · {mode.toUpperCase()}</span><strong>{target.glyph}</strong><small>Scan the whole field. The distractors are intentionally varied.</small></div><div className="focus-grid">{Array.from({length:GRID_SIZE},(_,i)=><button key={round+"-"+i} className={"focus-cell "+(visible&&i===targetCell?"focus-target":"")} onClick={()=>choose(i)} aria-label={visible&&i===targetCell?target.label:"field position"}>{visible&&i===targetCell?target.glyph:""}</button>)}</div><div className="live-stats"><span>STREAK <b>{streak}</b></span><span>HITS <b>{hits}</b></span><span>MISS <b>{mistakes}</b></span><span>MODE <b>{mode}</b></span></div><p className="game-hint">Do not memorize the layout. Every round can change the entire visual language.</p></section>}
 {finished&&<section className="result-card"><div className="eyebrow">CHALLENGE COMPLETE</div><div className="result-score">{score}</div><div className="result-label">FOCUS SCORE</div><div className="result-stats"><div><strong>{hits}</strong><span>correct</span></div><div><strong>{mistakes}</strong><span>misses</span></div><div><strong>{bestStreak}</strong><span>best streak</span></div></div><p>{score>=80?"Strong visual control. Try again if you want to recover or beat your best — not to extend the session.":"You can recover. Change your search strategy, then make one deliberate attempt."}</p><div className="cta-row"><button className="btn btn-primary" onClick={start}>Play another mix</button><Link href="/" className="btn btn-secondary">I am done</Link></div></section>}
 </main>;
}