"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

const BANK_ROUNDS = 5;
const BASE_WAIT_MS = 3000;
const BREAK_TARGET_MS = 96000;
const LAST_KEY = "forge.patience.lastScore";
const reflectionPrompts = ["Reflect on your day. What actually mattered today?","Set one target for the rest of today that you will be glad you completed.","Think about a goal you care about. What is one small step you can take toward it?","Imagine you could restart today. How would you organize your perfect day?","What deserves more of your attention than your phone right now?","Picture the person you want to become. What would that person do next?"];

export default function PatienceChallenge(){
 const[started,setStarted]=useState(false),[finished,setFinished]=useState(false),[round,setRound]=useState(0),[elapsed,setElapsed]=useState(0),[banked,setBanked]=useState(0),[early,setEarly]=useState(0),[breakMode,setBreakMode]=useState(false),[breakElapsed,setBreakElapsed]=useState(0),[previousBreak,setPreviousBreak]=useState(0);
 const waitMs=BASE_WAIT_MS*Math.pow(2,round), ready=elapsed>=waitMs;
 useEffect(()=>{if(!started||finished||breakMode)return;const t=window.setInterval(()=>setElapsed(v=>v+50),50);return()=>window.clearInterval(t)},[started,finished,breakMode]);
 useEffect(()=>{if(!breakMode)return;const t=window.setInterval(()=>setBreakElapsed(v=>v+250),250);return()=>window.clearInterval(t)},[breakMode]);
 const beginRound=()=>{setElapsed(0)};
 const begin=()=>{setStarted(true);setFinished(false);setBreakMode(false);setRound(0);setBanked(0);setEarly(0);setElapsed(0);setBreakElapsed(0);setPreviousBreak(Number(window.localStorage.getItem(LAST_KEY)||0));};
 const choose=()=>{if(!started||finished||breakMode)return;if(!ready){setEarly(v=>v+1);setRound(v=>v+1);beginRound();return;}if(round>=BANK_ROUNDS-1){setBanked(v=>v+1);setBreakMode(true);setBreakElapsed(0);return;}setBanked(v=>v+1);setRound(v=>v+1);beginRound();};
 const collect=()=>{const seconds=Math.floor(breakElapsed/1000);setPreviousBreak(Number(window.localStorage.getItem(LAST_KEY)||0));window.localStorage.setItem(LAST_KEY,String(seconds));setFinished(true);setBreakMode(false);};
 const improvement=breakElapsed/1000-previousBreak;
 return <main className="game-shell"><div className="game-topbar"><Link href="/" className="game-back">← FORGE</Link><div className="game-progress">{breakMode?"PHONE BREAK":started&&!finished?`ROUND ${round+1}/6`:"PATIENCE"}</div></div>
 {!started&&<section className="game-intro"><div className="eyebrow">PATIENCE · DELAYED REWARD</div><h1>Make waiting harder—one round at a time.</h1><p>The reward is deliberately delayed. Each time you bank it, the next wait doubles: 3s, 6s, 12s, 24s, then 48s. The final stage moves the challenge away from the screen.</p><div className="rule-pills"><span>3 → 48 seconds</span><span>Reward doubles in delay</span><span>Phone-away finish</span></div><button className="btn btn-primary" onClick={begin}>Start Patience</button></section>}
 {started&&!finished&&!breakMode&&<section className="game-stage"><div className="target-card"><span>REWARD BUILDING</span><strong>{ready?"FULL REWARD AVAILABLE":"WAIT"}</strong></div><div className="patience-meter"><div className="patience-fill" style={{width:`${Math.min(100,(elapsed/waitMs)*100)}%`}}/></div><div className="patience-value">{ready?"FULL REWARD AVAILABLE":"NEXT REWARD IN "+Math.max(0,Math.ceil((waitMs-elapsed)/1000))+"s"}</div><button className={`btn ${ready?"btn-primary":"btn-secondary"} patience-action`} onClick={choose}>{ready?"Bank full reward":"Take the early option"}</button><div className="live-stats"><span>ROUND <b>{round+1}/6</b></span><span>WAIT <b>{Math.ceil(waitMs/1000)}s</b></span><span>BANKED <b>{banked}</b></span></div><p className="game-hint">{ready?"You waited. Choose deliberately.":"Notice the urge to reach for the quick reward. You can wait."}</p></section>}
 {breakMode&&!finished&&<section className="game-stage patience-break"><div className="eyebrow">THE FINAL PATIENCE TEST</div><h1>Now leave the phone.</h1><p className="break-lead">Put the phone down, lock it, or close FORGE completely. Your final reward grows while you are away. The longer you stay away, the more you bank.</p><div className="break-clock"><span>TIME AWAY</span><strong>{Math.floor(breakElapsed/1000)}s</strong></div><div className="break-reward">+{Math.floor(breakElapsed/1000)} PATIENCE POINTS</div><div className="reflection-card"><span>WHILE YOU WAIT</span><p>{reflectionPrompts[Math.floor(breakElapsed/15000)%reflectionPrompts.length]}</p></div><div className="break-stats"><div><span>TARGET</span><strong>{BREAK_TARGET_MS/1000}s</strong></div><div><span>LAST BREAK</span><strong>{previousBreak?previousBreak+"s":"—"}</strong></div></div><p className="break-guidance">The goal is not to watch this timer. Leave the phone and come back when you are ready to collect your reward. There is no need to stay on this screen.</p><button className="btn btn-primary patience-collect" onClick={collect}>Collect reward</button></section>}
 {finished&&<section className="result-card patience-result"><div className="eyebrow">PATIENCE COMPLETE</div><div className="result-score">{Math.floor(breakElapsed/1000)}</div><div className="result-label">PHONE-FREE PATIENCE POINTS</div><div className="result-stats"><div><strong>{banked}</strong><span>banked rounds</span></div><div><strong>{Math.floor(breakElapsed/1000)}s</strong><span>phone-free</span></div><div><strong>{improvement>=0?"+":""}{Math.floor(improvement)}s</strong><span>vs last break</span></div></div><div className="comparison-card"><strong>{previousBreak?"You are competing with your previous self.":"You just created your baseline."}</strong><p>{previousBreak?`Last break: ${previousBreak}s. This break: ${Math.floor(breakElapsed/1000)}s.`:"Next time, see whether you can beat this record."}</p></div><p>Improvement means having more control over when you use your phone—not spending more time inside FORGE.</p><div className="cta-row"><button className="btn btn-primary" onClick={begin}>Run Patience again</button><Link href="/" className="btn btn-secondary">I'm done</Link></div></section>}
 </main>;
}
